const seed=[
{id:"001",title:"Aurora Wings",type:"Cosmetics",edition:"Java + Bedrock",server:"Northstar Network",seller:"Northstar",price:249,icon:"✦",badge:"FEATURED",desc:"Community showcase listing. Replace with an authorized catalog item before launch.",featured:1,created:9},
{id:"002",title:"Titan Rank",type:"Ranks",edition:"Java",server:"Example Network",seller:"ExampleSeller",price:599,icon:"♜",badge:"POPULAR",desc:"Sample server-rank listing demonstrating the production UI.",featured:1,created:8},
{id:"003",title:"Nether Explorer Set",type:"Gear",edition:"Bedrock",server:"Cobalt Realms",seller:"Cobalt",price:399,icon:"◇",badge:"NEW",desc:"Sample gear listing. Production availability would be verified.",featured:1,created:7},
{id:"004",title:"Skyblock Cosmetic Pack",type:"Cosmetics",edition:"Java",server:"Cloud District",seller:"CloudDistrict",price:179,icon:"☁",badge:"NEW",desc:"Sample cosmetic bundle for marketplace discovery.",created:6},
{id:"005",title:"5,000 Server Credits",type:"Server Credits",edition:"Java + Bedrock",server:"Example SMP",seller:"ExampleSMP",price:99,icon:"◆",badge:"REVIEW",desc:"Sample only. Server currencies require rules and compliance review.",created:5},
{id:"006",title:"Frost Ranger Skin",type:"Cosmetics",edition:"Bedrock",server:"Frostfall",seller:"Frostfall",price:129,icon:"❄",badge:"TRENDING",desc:"Sample skin/cosmetic card.",featured:1,created:4},
{id:"007",title:"Builder Pro Package",type:"Other",edition:"Java",server:"CraftPeak",seller:"CraftPeak",price:299,icon:"✚",badge:"COMMUNITY",desc:"Fictional bundle showing a broader listing type.",created:3},
{id:"008",title:"Seasonal Cosmetic Bundle",type:"Cosmetics",edition:"Java + Bedrock",server:"Pixel Harbor",seller:"PixelHarbor",price:349,icon:"✺",badge:"LIMITED",desc:"Sample seasonal product card.",featured:1,created:2},
{id:"009",title:"Starter Kit",type:"Gear",edition:"Java",server:"Cavebound",seller:"Cavebound",price:149,icon:"◇",badge:"COMMUNITY",desc:"Sample starter-kit listing.",created:1}];
const KEY="blockbuy_pro_v1";let state=JSON.parse(localStorage.getItem(KEY)||"null")||{listings:seed,favs:[],name:"Guest",theme:"dark"};
const $=x=>document.getElementById(x),save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const initial=s=>(s||"?")[0].toUpperCase();
function toast(s){$("toast").textContent=s;$("toast").classList.add("show");clearTimeout(window.t);window.t=setTimeout(()=>$("toast").classList.remove("show"),2800)}
function close(){document.querySelectorAll(".modal").forEach(x=>x.classList.remove("open"))}
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=close);document.querySelectorAll(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)close()});
function cards(arr){return arr.map(x=>`<article class="product"><div class="product-image"><span class="badge">${esc(x.badge)}</span><button class="heart ${state.favs.includes(x.id)?"active":""}" data-fav="${x.id}">${state.favs.includes(x.id)?"♥":"♡"}</button><div class="product-icon">${x.icon}</div></div><div class="product-body"><div class="meta"><span>${esc(x.type)}</span><span>${esc(x.edition)}</span></div><h3>${esc(x.title)}</h3><div class="desc">${esc(x.desc)}</div><div class="seller"><span class="avatar">${initial(x.seller)}</span>${esc(x.seller)} · ${esc(x.server)}</div><div class="foot"><div class="price">₹${Number(x.price).toLocaleString("en-IN")}<small>LISTED PRICE</small></div><button class="view" data-view="${x.id}">View listing →</button></div></div></article>`).join("")}
function current(){let q=$("search").value.toLowerCase().trim(),ed=$("edition").value,ty=$("type").value,a=state.listings.filter(x=>(!q||`${x.title} ${x.server} ${x.seller} ${x.type} ${x.desc}`.toLowerCase().includes(q))&&(!ed||x.edition===ed)&&(!ty||x.type===ty));let s=$("sort").value;if(s==="low")a.sort((x,y)=>x.price-y.price);if(s==="high")a.sort((x,y)=>y.price-x.price);if(s==="new")a.sort((x,y)=>y.created-x.created);if(s==="featured")a.sort((x,y)=>(y.featured||0)-(x.featured||0));return a}
function renderChips(){let cs=["All","Cosmetics","Gear","Ranks","Server Credits","Other"];$("chips").innerHTML=cs.map(c=>`<button class="chip ${($("type").value===""&&c==="All")||$("type").value===c?"active":""}" data-c="${esc(c)}">${c}</button>`).join("");document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{$("type").value=b.dataset.c==="All"?"":b.dataset.c;render()})}
function wire(){document.querySelectorAll("[data-fav]").forEach(b=>b.onclick=e=>{e.stopPropagation();let id=b.dataset.fav;state.favs=state.favs.includes(id)?state.favs.filter(x=>x!==id):[...state.favs,id];save();render()});document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>showDetail(b.dataset.view))}
function render(){renderChips();let a=current();$("catalog").innerHTML=a.length?cards(a):'<div class="empty"><b>No listings match.</b><p>Try another search or filter.</p></div>';$("resultText").textContent=`${a.length} result${a.length===1?"":"s"}`;$("listingStat").textContent=state.listings.length;let fav=state.favs.map(id=>state.listings.find(x=>x.id===id)).filter(Boolean);$("favoritesGrid").innerHTML=fav.length?cards(fav):'<div class="empty"><b>No saved listings yet.</b><p>Tap ♡ on a listing to save it.</p></div>';$("favCount").textContent=state.favs.length;$("profileName").textContent=state.name;$("grid").classList.toggle("active",!$("catalog").classList.contains("list-mode"));$("list").classList.toggle("active",$("catalog").classList.contains("list-mode"));document.body.classList.toggle("light",state.theme==="light");wire()}
function showDetail(id){let x=state.listings.find(a=>a.id===id);$("detail").innerHTML=`<div class="detail"><div class="detail-art">${x.icon}</div><div><div class="eyebrow">${esc(x.badge)} · ${esc(x.edition)}</div><h2>${esc(x.title)}</h2><p class="muted">${esc(x.desc)}</p><div class="detail-price">₹${Number(x.price).toLocaleString("en-IN")}</div><p class="muted"><b>Server:</b> ${esc(x.server)}<br><b>Seller:</b> ${esc(x.seller)}<br><b>Category:</b> ${esc(x.type)}</p><div class="warning">Checkout is intentionally not enabled yet. Connect a secure backend only after seller authorization, platform-rule review, payment setup and moderation are in place.</div><button class="btn ghost full" onclick="close()">Close</button></div></div>`;$("detailModal").classList.add("open")}
$("search").oninput=render;$("edition").onchange=render;$("type").onchange=render;$("sort").onchange=render;
$("clear").onclick=()=>{$("search").value="";$("edition").value="";$("type").value="";$("sort").value="featured";render()};
$("grid").onclick=()=>{$("catalog").classList.remove("list-mode");render()};$("list").onclick=()=>{$("catalog").classList.add("list-mode");render()};
$("themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";save();render()};
$("profileBtn").onclick=()=>{$("name").value=state.name==="Guest"?"":state.name;$("profileModal").classList.add("open")};
$("saveName").onclick=()=>{state.name=$("name").value.trim()||"Guest";save();close();render();toast("Profile saved on this device.")};
$("openSell").onclick=$("heroSell").onclick=()=>$("sellModal").classList.add("open");
$("sellForm").onsubmit=e=>{e.preventDefault();state.listings.unshift({id:"u-"+Date.now(),title:$("ft").value.trim(),price:+$("fp").value,type:$("fc").value,edition:$("fe").value,server:$("fs").value.trim(),seller:$("fu").value.trim(),desc:$("fd").value.trim(),icon:"◆",badge:"YOUR LISTING",created:Date.now()});save();e.target.reset();close();render();location.hash="market";toast("Listing saved locally — not published to buyers yet.")};
render();
